Reorganize scripts folder. Remove some scripts. Wrap compression verification with pragmas to speed up the general use case. Fix diagram generator script. compare new compression- no comp ratio. Gained performance 36%; Row 66%; Column 65%. (+10% over previous results)

diff --git a/scripts/slurm/scat b/scripts/slurm/scat
--- a/scripts/slurm/scat
+++ b/scripts/slurm/scat
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+srun=`which srun`
+if [ ! -x $srun ];then
+  echo "error: this script requires SLURM."
+  exit 1
+fi
+
 cat ./slurm-$1.out
 
 
diff --git a/scripts/slurm/sless b/scripts/slurm/sless
--- a/scripts/slurm/sless
+++ b/scripts/slurm/sless
@@ -1,3 +1,10 @@
 #!/bin/bash
 
+srun=`which srun`
+if [ ! -x $srun ];then
+  echo "error: this script requires SLURM."
+  exit 1
+fi
+
+
 less ./slurm-$1.out
